using Content.Client.UserInterface.Controls;
using Content.Client.Popups;
using Content.Shared.Access.Systems;
using Content.Shared.Teleportation.Components;
using Content.Shared.Telescience;
using Content.Shared.Telescience.Components;
using Content.Shared.Telescience.Ui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Shared.Map;
using Robust.Shared.Timing;

namespace Content.Client.Telescience.Ui;

[GenerateTypedNameReferences]
public sealed partial class TeleframeConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    private readonly AccessReaderSystem _accessReaderSystem = default!;
    private readonly PopupSystem _popupSystem = default!;
    private float _accumulator;
    private static readonly float UpdateRate = 1f / 10f;
    private readonly SharedTransformSystem _transform;
    private HashSet<TeleportPoint>? _knownBeacons;
    private Entity<TeleframeConsoleComponent, TransformComponent>? _console;
    private EntityUid? _user;
    private MapCoordinates? _coords;
    private TeleportPoint? _currentBeacon;
    private Vector2i? _currentCoords;

    public event Action<TeleframeActivateMessage>? OnActivated;

    public TeleframeConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _transform = _entMan.System<SharedTransformSystem>();
        _accessReaderSystem = _entMan.System<AccessReaderSystem>();

        CoordsX.OnValueChanged += e => OnCoordsChanged(new((int)e.Value, (int)CoordsY.Value));
        CoordsY.OnValueChanged += e => OnCoordsChanged(new((int)CoordsX.Value, (int)e.Value));

        SendToButton.OnPressed += _ => SendActivateMessage(TeleframeActivationMode.Send);
        ReceiveFromButton.OnPressed += _ => SendActivateMessage(TeleframeActivationMode.Receive);
    }
    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        _accumulator -= (float)_timing.FrameTime.TotalSeconds;
        if (_accumulator <= 0f)
        {
            _accumulator = MathF.Max(0f, _accumulator + UpdateRate);
            UpdateState(_console!.Value, _user!.Value);
        }
    }

    public void UpdateState(Entity<TeleframeConsoleComponent, TransformComponent> ent, EntityUid? user)
    {
        _console = ent;
        _user = user;

        _coords = _transform.GetMapCoordinates(ent.Owner, ent.Comp2);

        TeleportCheck(ent, false, null, false);
    }

    private void OnCoordsChanged(Vector2i coords)
    {
        var ent = _console!.Value;

        bool coordsValid;

        var logMan = IoCManager.Resolve<ILogManager>();
        var log = logMan.RootSawmill;

        _currentBeacon = null; //if typing in text, invalidate beacon teleport
        var message = Loc.GetString("teleporter-summary-insufficient");
        var coordsLength = Math.Pow(Math.Pow(coords.X, 2) + Math.Pow(coords.Y, 2), 0.5); //Vector 2i .Length overflows at high values

        if (ent.Comp1.MaxRange == null || coordsLength < ent.Comp1.MaxRange + _transform.GetMapCoordinates(ent).Position.Length())
        { //sanity check distance of teleport from teleframe console. This is mostly just to stop stupidly high teleports to millions of tiles out and shouldn't effect normal gameplay
            coordsValid = true;
        } //the system has a seperate check later that prevents you teleporting to empty space, so no blind teleports to say, get rid of a body.
        else
        {
            message = Loc.GetString("teleporter-summary-bigrange", ("range", ent.Comp1.MaxRange));
            coordsValid = false;
        }

        if (coordsValid)
        {
            message = Loc.GetString("teleporter-summary-custom", ("X", coords.X), ("Y", coords.Y));
            _currentCoords = coords;
        }
        else
        {
            _currentCoords = null;
        }

        TeleportCheck(ent, coordsValid, message);
    }

    /// <summary>
    /// Switch to beacon mode if a beacon is clicked on in the UI, and set teleport target to its coordinates
    /// </summary>
    /// <param name="beacon">clicked beacon</param>
    private void OnBeaconClicked(TeleportPoint beacon)
    {
        _currentCoords = null;
        _currentBeacon = beacon;
        TeleportCheck(_console!.Value, true, Loc.GetString("teleporter-summary-beacon", ("beacon", beacon.Location)));
    }

    /// <summary>
    /// Send the teleport message to initiate teleportation
    /// </summary>
    /// <param name="mode"></param>
    private void SendActivateMessage(TeleframeActivationMode mode)
    {
        TeleframeActivateMessage msg;

        if (_currentCoords is { } coords) //if we used coordinates, collate the X/Y Map coordinates and go somewhere on the current map
            msg = new TeleframeActivateMessage(new MapCoordinates(coords.X, coords.Y, _coords!.Value.MapId), Loc.GetString("teleporter-target-custom"), mode, NetEntity.Invalid);
        else if (_currentBeacon is { } beacon) //if we used beacons, get the map coordinates of the beacon, its name, and attach the entity itself for easier predictive teleportation
            msg = new TeleframeActivateMessage(_transform.GetMapCoordinates(_entMan.GetEntity(beacon.TelePoint)), beacon.Location, mode, beacon.TelePoint);
        else
            return;

        OnActivated?.Invoke(msg);
        TeleportCheck(_console!.Value, false, Loc.GetString("teleporter-summary-notready"));
    }

    /// <summary>
    /// Get valid beacons only, also make sure beacons exist!
    /// </summary>
    /// <param name="totalList"></param>
    /// <returns></returns>
    private IEnumerable<TeleportPoint> GetValidBeacons(IEnumerable<TeleportPoint> totalList)
    {
        foreach (var beacon in totalList)
        {
            if (!_entMan.TryGetEntity(beacon.TelePoint, out var beaconEnt))
                continue;

            if (!_entMan.TryGetComponent<TeleframeBeaconComponent>(beaconEnt, out var beaconComp))
                continue;

            if (beaconComp.ValidBeacon)
                yield return beacon;
        }
    }

    /// <summary>
    /// Get teleframe charge state for UI
    /// </summary>
    /// <returns>string station what that charge state is</returns>
    private string GetChargeState(Entity<TeleframeComponent> ent)
    {
        if (ent.Comp.IsPowered == false)
            return Loc.GetString("teleporter-unpowered");

        if (_entMan.TryGetComponent<TeleframeChargingComponent>(ent.Owner, out var charge))
        {
            var timeLeft = (int)(charge.EndTime - _timing.CurTime).TotalSeconds;
            return Loc.GetString("teleporter-charging", ("time", timeLeft));
        }

        if (_entMan.TryGetComponent<TeleframeRechargingComponent>(ent.Owner, out var recharge))
        {
            if (recharge.Pause == false)
            {
                var timeLeft = (int)(recharge.EndTime - _timing.CurTime).TotalSeconds;
                return Loc.GetString("teleporter-recharging", ("time", timeLeft));
            }
            else
            {
                return Loc.GetString("teleporter-recharging", ("time", "paused"));
            }
        }

        return Loc.GetString("teleporter-active");
    }


    /// <summary>
    /// check if teleportation console and linked teleframe are valid
    /// return true if they are (doesn't mean teleportation is possible)
    /// check should be performed any time teleportation possibility changes
    /// check should be performed consistently outside this too, not sure how to do that, could just add a refresh button.
    /// </summary>
    /// <param name="ent"></param>
    /// <param name="buttons">Default button state if checks succeed</param>
    /// <param name="message">Default message to send if checks succeed</param>
    /// <param name="change">did anything change, this function gets called for draw checks too</param>
    /// <returns>whether teleframe check finished in an expected manner</returns>
    private bool TeleportCheck(Entity<TeleframeConsoleComponent> ent, bool buttons, string? message, bool change = true)
    {
        if (_user == null || _console == null) //check player and console are not null
            return false;

        if (_knownBeacons == null || !Equals(_knownBeacons, ent.Comp.BeaconList))
        {
            _knownBeacons = ent.Comp.BeaconList;
            var beacons = GetValidBeacons(ent.Comp.BeaconList);
            AddBeaconButtons(beacons);
        }

        if (ent.Comp.LinkedTeleframe is { } linked)
        {
            var meta = _entMan.GetComponent<MetaDataComponent>(linked);
            if (!_entMan.TryGetComponent<TeleframeComponent>(linked, out var tpComp))
                return false;

            SetLinkName(Loc.GetString("teleporter-linked-to", ("name", meta.EntityName), ("state", GetChargeState((linked, tpComp))))); //kind of want a sprite here as well

            if (!tpComp.IsPowered || !tpComp.ReadyToTeleport)
            {
                UpdateTeleportButtons(false);
                UpdateTeleportSummary(Loc.GetString("teleporter-summary-notready"));
                return true;
            }
        }
        else
        {
            SetLinkName(Loc.GetString("teleporter-linked-to", ("name", Loc.GetString("teleporter-linked-default")), ("state", Loc.GetString("teleporter-linked-default"))));
            UpdateTeleportButtons(false);
            UpdateTeleportSummary(Loc.GetString("teleporter-summary-unavailable"));
            return true;
        }

        if (!_accessReaderSystem.IsAllowed(_user.Value, _console.Value)) //check player has the right access
        {
            UpdateTeleportButtons(false);
            UpdateTeleportSummary(Loc.GetString("teleport-console-access-denied"));
            return true;
        }

        if (change) //change for specific updates but not for continuous draw checks
        {
            UpdateTeleportButtons(buttons);

            if (message != null)
                UpdateTeleportSummary(message);
        }

        return true;
    }

    /// <summary>
    /// Populate teleport beacon list
    /// </summary>
    /// <param name="beacons"></param>
    private void AddBeaconButtons(IEnumerable<TeleportPoint> beacons)
    {
        BeaconButtonContainer.RemoveAllChildren();

        foreach (var beacon in beacons)
        {
            var button = new TeleframeConsoleBeaconButton(beacon);
            button.OnPressed += _ => OnBeaconClicked(beacon);
            BeaconButtonContainer.AddChild(button);
        }
    }

    /// <summary>
    /// Populate name of teleframe the console is linked to, or say "None" if not linked
    /// </summary>
    /// <param name="link"></param>
    private void SetLinkName(string link)
    {
        LinkLabel.Text = link;
    }

    /// <summary>
    /// Update text describing current teleframe possibility, or reason if not possible
    /// </summary>
    /// <param name="summary"></param>
    private void UpdateTeleportSummary(string summary)
    {
        SummaryLabel.Text = summary;
    }

    /// <summary>
    /// Update Send and Receive buttons depending on whether teleportation is possible
    /// </summary>
    /// <param name="valid">true if possible, false if not</param>
    private void UpdateTeleportButtons(bool valid)
    {
        SendToButton.Disabled = !valid;
        ReceiveFromButton.Disabled = !valid;
    }

}
